stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: git.exp.univie.ac.at:4567
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  #IMAGE_TAG: cpu-dev:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_cpu:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE -f Dockerfile.cpu .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - packer

build_gpu:
  stage: build
  script:
    - nvidia-docker build -t magnum.af-dev -f Dockerfile .
  tags:
    - gpu

test_cpu:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run --rm $CONTAINER_TEST_IMAGE ./tests/runall.sh
  tags:
    - packer

test_gpu:
  stage: test
  script:
    - nvidia-docker run --rm -t magnum.af-dev ./tests/runall.sh
  tags:
    - gpu

deploy_on_master_only:
  stage: deploy
  only:
    - master
  tags:
    - gpu
  script:
    - docker tag magnum.af-dev magnum.af
    - docker build -t magnum.af-docu -f Dockerfile.docu .
    - scripts/get_docu_from_image.sh magnum.af-docu
  artifacts:
    paths:
      - html/
      - latex/refman.pdf
