test: 
  script:
    - docker build -t afcpusrc -f Dockerfile.cpu .
    - docker run -t afcpusrc /magnum.af/tests/runall.sh /magnum.af
    - docker build -t afopenclsrc -f Dockerfile.opencl .
    - docker run --device=/dev/nvidia3 --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools -t afopenclsrc /magnum.af/tests/runall.sh /magnum.af
  tags:
  - packer # Currently set only to select GTO
