test_cpu: 
  script:
    - docker build -t magnum.af.cpu -f Dockerfile.cpu .
    - docker run -t magnum.af.cpu /magnum.af/tests/unit/cpp/runall.sh /magnum.af
    - docker run -t magnum.af.cpu /magnum.af/tests/integration/cpp/runall.sh /magnum.af
    - docker run -t magnum.af.cpu /magnum.af/tests/runall.sh /magnum.af
  tags:
    - docker
    - opencl

#test_gpu:
#  script:
#    - docker build -t magnum.af.opencl -f Dockerfile.opencl .
#    - docker run --device=/dev/nvidia3 --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools -t magnum.af.opencl /magnum.af/tests/unit/cpp/runall.sh /magnum.af
#    - docker run --device=/dev/nvidia3 --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools -t magnum.af.opencl /magnum.af/tests/integration/cpp/runall.sh /magnum.af
#    - docker run --device=/dev/nvidia3 --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools -t magnum.af.opencl /magnum.af/tests/runall.sh /magnum.af
#  tags:
#    - gpu
