test: 
  script:
    - docker build -t afcpusrc -f Dockerfile.cpu .
    - docker run -t afcpusrc /pth-mag/tests/runall.sh /pth-mag
    - docker build -t afopenclsrc -f Dockerfile.opencl .
    - docker run --device=/dev/nvidia3 --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools -t afopenclsrc /pth-mag/tests/runall.sh /pth-mag
  tags:
  - packer # Currently set only to select GTO
