test: 
  script:
    - docker build -t afcpusrc -f Dockerfile.cpu .
    - docker run -t afcpusrc /pth-mag/tests/runall.sh /pth-mag
  tags:
  - docker
  - deploy # Currently set only to select floarian-CP01 runner as Klaus has no space on disk
