stages:
  - build
  - test
  - deploy

build_cpu:
  stage: build
  script:
    - docker build -t magnum.af.cpu-dev -f Dockerfile.cpu .
    - scripts/get_docu_from_image.sh && rm -r latex
  artifacts:
    paths:
      - html/
  tags:
    - packer

build_gpu:
  stage: build
  script:
    - nvidia-docker build -t magnum.af-dev -f Dockerfile .
  tags:
    - gpu

test_cpu:
  stage: test
  script:
    - docker run --rm -t magnum.af.cpu-dev ./tests/runall.sh
  tags:
    - packer

test_gpu:
  stage: test
  script:
    - nvidia-docker run --rm -t magnum.af-dev ./tests/runall.sh
  tags:
    - gpu

deploy_on_master_only:
  stage: deploy
  only:
    - master
  tags:
    - gpu
  script:
    - nvidia-docker build -t magnum.af -f Dockerfile .
