test_cpu: 
  script:
    - docker build -t magnum.af.cpu-dev -f Dockerfile.cpu .
    - docker run --rm -t magnum.af.cpu-dev ./tests/runall.sh .
  tags:
    - packer

test_gpu:
  script:
    - nvidia-docker build -t magnum.af-dev -f Dockerfile .
    - nvidia-docker run --rm -t magnum.af-dev ./tests/runall.sh .
  tags:
    - gpu

deploy_on_master_only:
  stage: deploy
  only:
    - master
  tags:
    - gpu
  script:
    - nvidia-docker build -t magnum.af -f Dockerfile .
