test_cpu: 
  script:
    - docker build -t magnum.af.cpu -f Dockerfile.cpu .
    - docker run --rm -t magnum.af.cpu .tests/runall.sh .
  tags:
    - packer

test_gpu:
  script:
    - nvidia-docker build -t magnum.af -f Dockerfile .
    - nvidia-docker run --rm -t magnum.af .tests/runall.sh .
  tags:
    - gpu
